In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tf.placeholder를 사용하기 위함
tf.set_random_seed(777)

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [3]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [4]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [5]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [6]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

In [7]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost:  2598.893 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]
 [ 69.79834 ]
 [100.468285]
 [ 73.146675]
 [117.17079 ]
 [106.953476]]
10 Cost:  12.217089 
Prediction:
 [[154.37231 ]
 [185.07695 ]
 [182.75241 ]
 [198.49669 ]
 [141.23367 ]
 [102.764694]
 [147.54459 ]
 [108.05685 ]
 [171.95518 ]
 [157.72067 ]]
20 Cost:  11.8052025 
Prediction:
 [[154.6922  ]
 [185.47464 ]
 [183.1368  ]
 [198.9231  ]
 [141.53386 ]
 [102.99955 ]
 [147.87163 ]
 [108.309875]
 [172.33943 ]
 [158.09494 ]]
30 Cost:  11.731593 
Prediction:
 [[154.68541]
 [185.47955]
 [183.13428]
 [198.92807]
 [141.53448]
 [103.01346]
 [147.88318]
 [108.32898]
 [172.3565 ]
 [158.129  ]]
40 Cost:  11.660123 
Prediction:
 [[154.67644 ]
 [185.4818  ]
 [183.12915 ]
 [198.93016 ]
 [141.53307 ]
 [103.025826]
 [147.89253 ]
 [108.34644 ]
 [172.371   ]
 [158.16061 ]]
50 Cost:  11.58932 
Prediction:
 [[154.66753 ]
 [185.

660 Cost:  8.334337 
Prediction:
 [[154.20499 ]
 [185.58586 ]
 [182.85167 ]
 [199.047   ]
 [141.43335 ]
 [103.67726 ]
 [148.41505 ]
 [109.322174]
 [173.13586 ]
 [159.85533 ]]
670 Cost:  8.2952385 
Prediction:
 [[154.19862]
 [185.58707]
 [182.84781]
 [199.04869]
 [141.4316 ]
 [103.68612]
 [148.4226 ]
 [109.33634]
 [173.14626]
 [159.87881]]
680 Cost:  8.25654 
Prediction:
 [[154.19228]
 [185.58824]
 [182.84395]
 [199.05038]
 [141.42982]
 [103.69492]
 [148.43016]
 [109.35044]
 [173.15659]
 [159.90216]]
690 Cost:  8.218192 
Prediction:
 [[154.18599 ]
 [185.58943 ]
 [182.84013 ]
 [199.05208 ]
 [141.42809 ]
 [103.703674]
 [148.43768 ]
 [109.3645  ]
 [173.16689 ]
 [159.92543 ]]
700 Cost:  8.180216 
Prediction:
 [[154.17972]
 [185.59059]
 [182.83633]
 [199.05376]
 [141.42632]
 [103.71238]
 [148.44518]
 [109.37852]
 [173.17711]
 [159.94858]]
710 Cost:  8.142607 
Prediction:
 [[154.17348 ]
 [185.59172 ]
 [182.83252 ]
 [199.05544 ]
 [141.42453 ]
 [103.721054]
 [148.45264 ]
 [109.39249 ]
 [173.187

1170 Cost:  6.751409 
Prediction:
 [[153.92137 ]
 [185.63155 ]
 [182.67519 ]
 [199.12665 ]
 [141.33989 ]
 [104.072975]
 [148.77052 ]
 [109.98791 ]
 [173.60039 ]
 [160.92113 ]]
1180 Cost:  6.7274942 
Prediction:
 [[153.91658 ]
 [185.63216 ]
 [182.67212 ]
 [199.1281  ]
 [141.338   ]
 [104.07969 ]
 [148.77693 ]
 [109.999886]
 [173.60828 ]
 [160.93956 ]]
1190 Cost:  6.703799 
Prediction:
 [[153.91182]
 [185.63277]
 [182.66907]
 [199.12952]
 [141.33612]
 [104.08638]
 [148.7833 ]
 [110.01183]
 [173.61612]
 [160.9579 ]]
1200 Cost:  6.680336 
Prediction:
 [[153.90709]
 [185.63335]
 [182.66602]
 [199.13094]
 [141.33421]
 [104.09302]
 [148.78963]
 [110.02373]
 [173.62392]
 [160.97615]]
1210 Cost:  6.6570983 
Prediction:
 [[153.90237]
 [185.63391]
 [182.66298]
 [199.13234]
 [141.3323 ]
 [104.09963]
 [148.79594]
 [110.0356 ]
 [173.63165]
 [160.9943 ]]
1220 Cost:  6.6340933 
Prediction:
 [[153.89769]
 [185.63449]
 [182.65997]
 [199.13376]
 [141.33041]
 [104.1062 ]
 [148.80225]
 [110.04742]
 [173.63

1660 Cost:  5.8134513 
Prediction:
 [[153.7163 ]
 [185.65114]
 [182.54   ]
 [199.19164]
 [141.24579]
 [104.36212]
 [149.06017]
 [110.53166]
 [173.93974]
 [161.72838]]
1670 Cost:  5.798566 
Prediction:
 [[153.71266]
 [185.65135]
 [182.53752]
 [199.19286]
 [141.24385]
 [104.36723]
 [149.0656 ]
 [110.54188]
 [173.94574]
 [161.74297]]
1680 Cost:  5.7838316 
Prediction:
 [[153.70909 ]
 [185.65154 ]
 [182.53508 ]
 [199.19409 ]
 [141.24191 ]
 [104.37232 ]
 [149.07103 ]
 [110.552086]
 [173.95172 ]
 [161.75749 ]]
1690 Cost:  5.7692137 
Prediction:
 [[153.7055 ]
 [185.65172]
 [182.53262]
 [199.19528]
 [141.23996]
 [104.37739]
 [149.07642]
 [110.56225]
 [173.95764]
 [161.77194]]
1700 Cost:  5.7547836 
Prediction:
 [[153.70198]
 [185.65192]
 [182.53021]
 [199.19652]
 [141.23804]
 [104.38243]
 [149.08182]
 [110.57239]
 [173.96356]
 [161.78633]]
1710 Cost:  5.740468 
Prediction:
 [[153.69846 ]
 [185.65208 ]
 [182.5278  ]
 [199.19772 ]
 [141.2361  ]
 [104.387436]
 [149.08719 ]
 [110.58249 ]
 [173.969

In [11]:
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[185.7536]]
Other scores will be  [[168.45357]
 [179.88739]]


In [ ]:
"""
shuffle_batch
min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch(
   [example, label], batch_size=batch_size, capacity=capacity,
   min_after_dequeue=min_after_dequeue)
"""