In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tf.placeholder를 사용하기 위함
tf.set_random_seed(777)

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [6]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [7]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [21]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.152361 
Prediction:
 [150.30936 185.18463 179.86536 198.34871 140.47197]
10 Cost:  2.1513767 
Prediction:
 [150.30962 185.18451 179.86551 198.34814 140.4724 ]
20 Cost:  2.1504261 
Prediction:
 [150.30988 185.1844  179.86568 198.3476  140.4728 ]
30 Cost:  2.1494305 
Prediction:
 [150.31015 185.18428 179.86586 198.34703 140.47322]
40 Cost:  2.1484618 
Prediction:
 [150.31044 185.1842  179.86604 198.34651 140.47366]
50 Cost:  2.1474957 
Prediction:
 [150.3107  185.18407 179.86621 198.34595 140.47406]
60 Cost:  2.1465323 
Prediction:
 [150.31094 185.18394 179.86636 198.34538 140.47447]
70 Cost:  2.1455429 
Prediction:
 [150.31123 185.18384 179.86655 198.34483 140.4749 ]
80 Cost:  2.144573 
Prediction:
 [150.31151 185.18372 179.86671 198.34428 140.47531]
90 Cost:  2.1436 
Prediction:
 [150.31177 185.1836  179.86687 198.34372 140.47572]
100 Cost:  2.1426454 
Prediction:
 [150.31206 185.1835  179.86707 198.34322 140.47617]
110 Cost:  2.1416867 
Prediction:
 [150.31232 185.1834  179

1120 Cost:  2.046185 
Prediction:
 [150.3395  185.17152 179.88419 198.28773 140.51775]
1130 Cost:  2.045259 
Prediction:
 [150.33975 185.1714  179.88435 198.28719 140.51814]
1140 Cost:  2.0443275 
Prediction:
 [150.34004 185.1713  179.88452 198.28665 140.51854]
1150 Cost:  2.0434291 
Prediction:
 [150.3403  185.17117 179.8847  198.28613 140.51894]
1160 Cost:  2.0425081 
Prediction:
 [150.34058 185.17105 179.88486 198.2856  140.51933]
1170 Cost:  2.0415647 
Prediction:
 [150.34085 185.17094 179.88503 198.28505 140.51974]
1180 Cost:  2.0406578 
Prediction:
 [150.34113 185.17084 179.88521 198.28453 140.52014]
1190 Cost:  2.0397365 
Prediction:
 [150.3414  185.17072 179.88538 198.284   140.52054]
1200 Cost:  2.0388126 
Prediction:
 [150.34166 185.1706  179.88553 198.28345 140.52094]
1210 Cost:  2.0379052 
Prediction:
 [150.34193 185.17047 179.88571 198.28293 140.52133]
1220 Cost:  2.0369818 
Prediction:
 [150.3422  185.17035 179.88586 198.28238 140.52173]
1230 Cost:  2.0360618 
Prediction:

In [ ]:
"""
이런 방식은 instance가 많아질 경우 좋지 않은 코드의 예시가 된다.
"""